# Client configuration file for Legendary Survival Overhaul
# Alterado para o Velvet Abyss: HUD, efeitos visuais e sonoros de temperatura desativados.

[hud]
	[hud.general]
		"Show Food Saturation Bar" = false
		"Show Vanilla Bar Animation Overlay" = true

	[hud.temperature]
		# How temperature is displayed. Accepted values: SYMBOL, NONE
		"Temperature Display Mode" = "NONE"
		"Temperature Display X Offset" = 0
		"Temperature Display Y Offset" = 0
		"Body Temperature Display X Offset" = 0
		"Body Temperature Display Y Offset" = 0
		# If enabled, player will see a foggy effect when the heat is high.
		"Heat Temperature Overlay" = false
		# If enabled, player will see a frost effect when the cold is low.
		"Cold Temperature Overlay" = false
		# If enabled, breathing sound can be heard while player faces harsh temperatures.
		"Breathing Sound Enabled" = false
		# Temperature threshold below which a cold breath effect is rendered by the player. -1000 disable the feature.
		"Cold Breath Temperature Threshold" = -1000.0
		"Temperature In Fahrenheit" = false

	[hud.temperature.wetness]
		"Wetness Indicator X Offset" = 0
		"Wetness Indicator Y Offset" = 0

[thirst]
	[thirst.tooltip]
		"Show Hydration Tooltip" = true
		"Merge Hydration And Saturation Tooltip" = false
		"Render the hydration saturation" = true
		"Low Hydration Effect" = true

	[thirst.hydration-bar]
		"Show Hydration Bar" = true
		"Render the hydration exhaustion" = true
		"Show Drink Preview" = true
		"Hydration Bar Offset X" = 0
		"Hydration Bar Offset Y" = 0
